version: 0.2

env:
  variables:
    GO_VERSION: 1.18.1

phases:
  install:
    commands:
      - echo Start install

  pre_build:
    commands:
      - echo login to AWS ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_BASE_URI
    
  build:
    commands:
      - echo Build started on `date`
      - echo replace repository path in dockerfile 
      - sed -i 's/REPOSITORY_BASE_URI/"${REPOSITORY_BASE_URI}"/g' Dockerfile
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_BASE_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_BASE_URI/$IMAGE_REPO_NAME:$IMAGE_TAG



